---
dependency:
  name: galaxy
  options:
    role-file: requirements.yml
lint:
  name: yamllint
driver:
  name: docker
platforms:
  - name: mitogen-opensuse-leap
    image: opensuse:leap
provisioner:
  name: ansible
  lint:
    name: ansible-lint
scenario:
  name: opensuse-leap
