---
sudo: required
language: python
services: docker

env:
  - version=">=2.4,<2.5" distro="alpine-latest"
  - version=">=2.5,<2.6" distro="alpine-latest"
  - version=">=2.6,<2.7" distro="alpine-latest"
  - version=">=2.4,<2.5" distro="alpine-edge"
  - version=">=2.5,<2.6" distro="alpine-edge"
  - version=">=2.6,<2.7" distro="alpine-edge"
  - version=">=2.4,<2.5" distro="archlinux"
  - version=">=2.5,<2.6" distro="archlinux"
  - version=">=2.6,<2.7" distro="archlinux"
  - version=">=2.4,<2.5" distro="centos-6" expectation="fail"
  - version=">=2.5,<2.6" distro="centos-6" expectation="fail"
  - version=">=2.6,<2.7" distro="centos-6" expectation="fail"
  - version=">=2.4,<2.5" distro="centos-latest"
  - version=">=2.5,<2.6" distro="centos-latest"
  - version=">=2.6,<2.7" distro="centos-latest"
  - version=">=2.4,<2.5" distro="debian-latest"
  - version=">=2.5,<2.6" distro="debian-latest"
  - version=">=2.6,<2.7" distro="debian-latest"
  - version=">=2.4,<2.5" distro="debian-stable"
  - version=">=2.5,<2.6" distro="debian-stable"
  - version=">=2.6,<2.7" distro="debian-stable"
  - version=">=2.4,<2.5" distro="debian-unstable"
  - version=">=2.5,<2.6" distro="debian-unstable"
  - version=">=2.6,<2.7" distro="debian-unstable"
  - version=">=2.4,<2.5" distro="fedora-latest"
  - version=">=2.5,<2.6" distro="fedora-latest"
  - version=">=2.6,<2.7" distro="fedora-latest"
  - version=">=2.4,<2.5" distro="fedora-rawhide"
  - version=">=2.5,<2.6" distro="fedora-rawhide"
  - version=">=2.6,<2.7" distro="fedora-rawhide"
  - version=">=2.4,<2.5" distro="opensuse-leap"
  - version=">=2.5,<2.6" distro="opensuse-leap"
  - version=">=2.6,<2.7" distro="opensuse-leap"
  - version=">=2.4,<2.5" distro="opensuse-tumbleweed"
  - version=">=2.5,<2.6" distro="opensuse-tumbleweed"
  - version=">=2.6,<2.7" distro="opensuse-tumbleweed"
  - version=">=2.4,<2.5" distro="ubuntu-artful"
  - version=">=2.5,<2.6" distro="ubuntu-artful"
  - version=">=2.6,<2.7" distro="ubuntu-artful"
  - version=">=2.4,<2.5" distro="ubuntu-latest"
  - version=">=2.5,<2.6" distro="ubuntu-latest"
  - version=">=2.6,<2.7" distro="ubuntu-latest"
  - version=">=2.4,<2.5" distro="ubuntu-devel"
  - version=">=2.5,<2.6" distro="ubuntu-devel"
  - version=">=2.6,<2.7" distro="ubuntu-devel"

matrix:
  allow_failures:
    - env: version=">=2.4,<2.5" distro="alpine-edge"
    - env: version=">=2.5,<2.6" distro="alpine-edge"
    - env: version=">=2.6,<2.7" distro="alpine-edge"
    - env: version=">=2.4,<2.5" distro="debian-unstable"
    - env: version=">=2.5,<2.6" distro="debian-unstable"
    - env: version=">=2.6,<2.7" distro="debian-unstable"
    - env: version=">=2.4,<2.5" distro="fedora-rawhide"
    - env: version=">=2.5,<2.6" distro="fedora-rawhide"
    - env: version=">=2.6,<2.7" distro="fedora-rawhide"
    - env: version=">=2.4,<2.5" distro="ubuntu-devel"
    - env: version=">=2.5,<2.6" distro="ubuntu-devel"
    - env: version=">=2.6,<2.7" distro="ubuntu-devel"

cache:
  - pip

install:
  - pip install --upgrade pip
  - pip install ansible"${version}"
  - pip install molecule
  - pip install docker

script:
  - if [ "${expectation}" = "fail" ] ; then ! molecule test --scenario-name "${distro}" ; else molecule test --scenario-name "${distro}" ; fi

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
  slack:
    secure: "lz4bncsSrtTmRME20hzFdfKkiZcaRLLKPftOulNQrzW6qjseGjerK7Z7ryy+mVjwX4W8UMwtJXoXCt+MnS5w3i0HQZIqLcRfZENGzp8rAVjH4cBJzhUGHmOnYyGCJNMeWxd6Y5j+qSPjfn7lbIoz71iSJw/LUXzH9fwD4bcCMvFZCJwfjYRYGxlmlCQNOhNz1My+7ck1BwPIlrZe+JPULSuQJqT00/y9sL1imaNAeijuyn+NV5TDx8EguSVtQlck9aJ6bcA9yNh0oJ/bKSLvfbVJ8C+n97b3dNSXEEsfjppzVeAL1FSqaop5gRJTBkjTqWpWnDe6bEGdC91BbgF2NSkbGRx63r6TQ0wlb4qBgIvDkbCrChJatIlZsWiYiEB7W1Hj65ZUWCystPHiPAg16+Eh6vvBlDonL5SKDxoRT1MHBGycq8wiBgtAMKwDKJxhAP2JmmiGW58qLdu+aj31s0zkadLx1f9xIoW7X4iNBAYTeoSgx3slSsB3x8SVqaGVmRwfdk4JLWpcaH/Lol8tNsWtYVmI1Ly+MH8nnivtP8w+VzkhiPa8bp4Bo/jTyvB8MSYGfOai6Vq6kTNqXooFzjT5pIGKmRP+THh0WsPLz9gR3zMcuTsX+8xrRCTz9Zsh+OjO1i3qSKOCSuVJPSu+qmFYoAHKcQKzx6sUfV9XTI8="
  email: false
