---
# tasks file for ara
- name: load default variables
  include_vars:
    file: default.yml

- name: load os-specific variables
  include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution }}.yml"
    - default.yml

- name: find site-package location
  command: python -c "import site; print(site.getsitepackages()[0])"
  register: mitogen_site_packages_path
  changed_when: false

- name: install mitogen
  unarchive:
    src: https://github.com/dw/mitogen/archive/stable.zip
    dest: "{{ mitogen_site_packages_path.stdout }}"
    remote_src: true
    creates: "{{ mitogen_site_packages_path.stdout }}/mitogen-stable"
  register: install_mitogen
  until: install_mitogen is succeeded
  retries: 3

- name: configure ansible to use mitogen
  ini_file:
    path: "{{ mitogen_ansible_file }}"
    section: defaults
    option: strategy_plugins
    value: "{{ mitogen_site_packages_path.stdout }}/mitogen-stable/ansible_mitogen/plugins/strategy"
  become: true

- name: configure ansible to use mitogen strategy
  ini_file:
    path: "{{ mitogen_ansible_file }}"
    section: defaults
    option: strategy
    value: mitogen_linear
  become: true
