---
# tasks file for mitogen
- name: include assert.yml
  include_tasks: assert.yml

- name: find site-package location
  command: "python{{ ansible_python.version.major }} -c 'import site; print(site.getsitepackages()[0])'"
  register: mitogen_site_packages_path
  changed_when: no
  check_mode: no

- name: create site-packages location
  file:
    path: "{{ mitogen_site_packages_path.stdout }}"
    state: directory
    mode: "0755"

- name: install mitogen
  unarchive:
    src: https://github.com/dw/mitogen/archive/stable.zip
    dest: "{{ mitogen_site_packages_path.stdout }}"
    remote_src: yes
    creates: "{{ mitogen_site_packages_path.stdout }}/mitogen-stable"
    mode: "0750"

- name: configure ansible to use mitogen
  ini_file:
    path: "{{ mitogen_ansible_file }}"
    section: defaults
    option: strategy_plugins
    value: "{{ mitogen_site_packages_path.stdout }}/mitogen-stable/ansible_mitogen/plugins/strategy"
    mode: "0644"
  become: yes

- name: configure ansible to use mitogen strategy
  ini_file:
    path: "{{ mitogen_ansible_file }}"
    section: defaults
    option: strategy
    value: mitogen_linear
    mode: "0644"
  become: yes
