---
dependency:
  name: galaxy
  options:
    role-file: requirements.yml
lint:
  name: yamllint
driver:
  name: docker
platforms:
  - name: mitogen-alpine-edge
    image: alpine:edge
    command: sh -c "while true ; do sleep 1 ; done"
provisioner:
  name: ansible
  lint:
    name: ansible-lint
scenario:
  name: alpine-edge
