---
dependency:
  name: galaxy
  options:
    role-file: requirements.yml
lint:
  name: yamllint
driver:
  name: docker
platforms:
  - name: mitogen-ubuntu-rolling
    image: ubuntu:rolling
provisioner:
  name: ansible
  lint:
    name: ansible-lint
scenario:
  name: ubuntu-rolling
