---
dependency:
  name: galaxy
  options:
    role-file: requirements.yml
driver:
  name: vagrant
  provider:
    name: virtualbox
lint:
  name: yamllint
platforms:
  - name: mitogen-debian
    box: debian/stretch64
  - name: mitogen-fedora
    box: fedora/28-cloud-base
provisioner:
  name: ansible
  lint:
    name: ansible-lint
  config_options:
    defaults:
      callback_plugins: /usr/lib/python2.7/site-packages/ara/plugins/callbacks
scenario:
  name: vagrant
verifier:
  name: goss
  lint:
    name: yamllint
