---
- name: Prepare
  hosts: all
  become: true
  gather_facts: true

  roles:
    - role: robertdebock.bootstrap
    - role: robertdebock.core_dependencies
    - role: robertdebock.epel
    - role: robertdebock.python_pip
